from __future__ import print_function
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
import numpy as np
from numpy import random
from PIL import Image
import glob
from keras import optimizers
from keras.models import load_model

from keras.losses import *

from keras.layers import Activation
from keras.layers.core import Flatten, Dense, Dropout
from keras.layers.convolutional import Convolution2D, MaxPooling2D, ZeroPadding2D
from keras.preprocessing.image import ImageDataGenerator

#CNN
#------------------------------------------------------

x_set = np.array([]).reshape(0, 128, 128, 3)
y_set = np.array([]).reshape(0)
for it in range(6):
    x_tmp = np.load("data1000/128_age/xtrain_128_" + str(it) + ".dat")
    y_tmp = np.load("data1000/128_age/ytrain_128_" + str(it) + ".dat")

    x_set = np.append(x_set, x_tmp, axis=0)
    y_set = np.append(y_set, y_tmp, axis=0)

trainSize = int(x_set.shape[0] * 0.7)
trainSize = int(x_set.shape[0] * 0.7)
validSize = int(x_set.shape[0] * 0.15)

x_train = x_set[:trainSize]
y_train = y_set[:trainSize]
x_val = x_set[trainSize:trainSize+validSize]
y_val = y_set[trainSize:trainSize+validSize]
x_test = x_set[trainSize+validSize:]
y_test = y_set[trainSize+validSize:]



epochs = 20
batch_size = 64
input_shape = (128, 128, 3)
data_augmentation = True


x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_val = x_val.astype('float32')
x_train /= 255
x_test /= 255
x_val /= 255

# model = load_model("keras_model.h5")
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape,
                 kernel_initializer="he_normal"))
model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer="he_normal"))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer="he_normal"))
model.add(Conv2D(32, (3, 3), activation='relu', kernel_initializer="he_normal"))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu', kernel_initializer="he_normal"))
model.add(Dropout(0.5))
model.add(Dense(1 ))

# opt = optimizers.Adam(lr=0.01)
opt = keras.optimizers.RMSprop(lr=0.001, rho=0.9, epsilon=1e-08, decay=0.0)


def myloss(y_true, y_pred):
  return mean_squared_error(y_true[0], y_pred)

model.compile(loss=mean_squared_error,
              optimizer=opt,
              metrics=['mae'])

if not data_augmentation:
  model.fit(x_train, y_train,
            batch_size=batch_size,
            epochs=epochs,
            verbose=1,
            validation_data=(x_test, y_test),
            shuffle=True)
  
  score = model.evaluate(x_test, y_test, verbose=1)
  print('Test loss:', score[0])
  print('Test accuracy:', score[1])
  
  model.save('age_reg_model.h5')
  
  pred = model.predict(x_test)
  for i in range(len(pred)):
    print(str(pred[i]) + " => " + str(y_test[i]))
  print('Test loss:', score[0])
  print('Test accuracy:', score[1])

  
  

else:
    print('Using real-time data augmentation.')
    # This will do preprocessing and realtime data augmentation:
    datagen = ImageDataGenerator(
        featurewise_center=False,  # set input mean to 0 over the dataset
        samplewise_center=False,  # set each sample mean to 0
        featurewise_std_normalization=False,  # divide inputs by std of the dataset
        samplewise_std_normalization=False,  # divide each input by its std
        zca_whitening=False,  # apply ZCA whitening
        rotation_range=5,  # randomly rotate images in the range (degrees, 0 to 180)
        width_shift_range=0.1,  # randomly shift images horizontally (fraction of total width)
        height_shift_range=0.1,  # randomly shift images vertically (fraction of total height)
        horizontal_flip=True,  # randomly flip images
        vertical_flip=False )  # randomly flip images

    # Compute quantities required for feature-wise normalization
    # (std, mean, and principal components if ZCA whitening is applied).
    datagen.fit(x_train)

    # Fit the model on the batches generated by datagen.flow().
    model.fit_generator(datagen.flow(x_train, y_train,
                       batch_size=batch_size),
                         steps_per_epoch=x_train.shape[0] // batch_size,
                         epochs=epochs,
                         validation_data=(x_val, y_val))
    score = model.evaluate(x_test, y_test, verbose=1)
    print('Test loss:', score[0])
    print('Test accuracy:', score[1])
    pred = model.predict(x_test)
    # print(pred)
    f = open("res.txt", "w")
    for i in range(len(pred)):
      ss = str(y_test[i]) + ";" + str(abs(np.around(pred[i])-y_test[i])) + ";" + str(np.around(pred[i])-y_test[i]) + "\n"
      f.write(ss)
      # print(str(pred[i]) + " => " + str(y_test[i]))
    print('Test loss:', score[0])
    print('Test accuracy:', score[1])


